Update and run i18n scripts. It now extracts the metadata widget name.
Added Keys:
"TodoList"

diff --git a/package/translate/merge b/package/translate/merge
--- a/package/translate/merge
+++ b/package/translate/merge
@@ -1,8 +1,9 @@
 #!/bin/sh
-# Version: 15
+# Version: 20
 
 # https://techbase.kde.org/Development/Tutorials/Localization/i18n_Build_Systems
-# Based on: https://github.com/psifidotos/nowdock-plasmoid/blob/master/po/Messages.sh
+# https://techbase.kde.org/Development/Tutorials/Localization/i18n_Build_Systems/Outside_KDE_repositories
+# https://invent.kde.org/sysadmin/l10n-scripty/-/blob/master/extract-messages.sh
 
 DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`
 plasmoidName=`kreadconfig5 --file="$DIR/../metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name"`
@@ -27,20 +28,47 @@ fi
 
 #---
 echo "[merge] Extracting messages"
-find "${packageRoot}" -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.qml' -o -name '*.js' | sort > "${DIR}/infiles.list"
+potArgs="--from-code=UTF-8 --width=200 --add-location=file --default-domain=\"${projectName}\""
 
+find "${packageRoot}" -name '*.desktop' | sort > "${DIR}/infiles.list"
 xgettext \
-	--from-code=UTF-8 \
-	-C -kde -ci18n -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 -ktr2i18n:1 -kI18N_NOOP:1 \
-	-kI18N_NOOP2:1c,2  -kN_:1 -kaliasLocale -kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
-	--files-from="infiles.list" \
-	--width=200 \
-	--add-location=file \
+	${potArgs} \
+	--files-from="${DIR}/infiles.list" \
+	--language=Desktop \
+	-D "${packageRoot}" \
+	-D "${DIR}" \
+	-o "template.pot.new" \
+	|| \
+	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
+
+sed -i 's/"Content-Type: text\/plain; charset=CHARSET\\n"/"Content-Type: text\/plain; charset=UTF-8\\n"/' "template.pot.new"
+
+# See Ki18n's extract-messages.sh for a full example:
+# https://invent.kde.org/sysadmin/l10n-scripty/-/blob/master/extract-messages.sh#L25
+# The -kN_ and -kaliasLocale keywords are mentioned in the Outside_KDE_repositories wiki.
+# We don't need -kN_ since we don't use intltool-extract but might as well keep it.
+# I have no idea what -kaliasLocale is used for. Googling aliasLocale found only listed kde1 code..
+# We don't need to parse -ki18nd since that'll extract messages from other domains.
+find "${packageRoot}" -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.qml' -o -name '*.js' | sort > "${DIR}/infiles.list"
+xgettext \
+	${potArgs} \
+	--files-from="${DIR}/infiles.list" \
+	-C -kde \
+	-ci18n \
+	-ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 \
+	-kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
+	-kxi18n:1 -kxi18nc:1c,2 -kxi18np:1,2 -kxi18ncp:1c,2,3 \
+	-kkxi18n:1 -kkxi18nc:1c,2 -kkxi18np:1,2 -kkxi18ncp:1c,2,3 \
+	-kI18N_NOOP:1 -kI18NC_NOOP:1c,2 \
+	-kI18N_NOOP2:1c,2 -kI18N_NOOP2_NOSTRIP:1c,2 \
+	-ktr2i18n:1 -ktr2xi18n:1 \
+	-kN_:1 \
+	-kaliasLocale \
 	--package-name="${widgetName}" \
-	--package-version="" \
 	--msgid-bugs-address="${bugAddress}" \
 	-D "${packageRoot}" \
 	-D "${DIR}" \
+	--join-existing \
 	-o "template.pot.new" \
 	|| \
 	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
@@ -123,8 +151,67 @@ for cat in $catalogs; do
 	# mv "$cat" "$cat.old"
 	mv "$cat.new" "$cat"
 done
+echo "[merge] Done merging messages"
 
+#---
+echo "[merge] Updating .desktop file"
+
+# Generate LINGUAS for msgfmt
+if [ -f "$DIR/LINGUAS" ]; then
+	rm "$DIR/LINGUAS"
+fi
+touch "$DIR/LINGUAS"
+for cat in $catalogs; do
+	catLocale=`basename ${cat%.*}`
+	echo "${catLocale}" >> "$DIR/LINGUAS"
+done
+
+cp -f "$DIR/../metadata.desktop" "$DIR/template.desktop"
+sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/template.desktop"
+
+msgfmt \
+	--desktop \
+	--template="$DIR/template.desktop" \
+	-d "$DIR/" \
+	-o "$DIR/new.desktop"
+
+# Delete empty msgid messages that used the po header
+if [ ! -z "$(grep '^Name=$' "$DIR/new.desktop")" ]; then
+	echo "[merge] Name in metadata.desktop is empty!"
+	sed -i '/^Name\[/ d' "$DIR/new.desktop"
+fi
+if [ ! -z "$(grep '^GenericName=$' "$DIR/new.desktop")" ]; then
+	echo "[merge] GenericName in metadata.desktop is empty!"
+	sed -i '/^GenericName\[/ d' "$DIR/new.desktop"
+fi
+if [ ! -z "$(grep '^Comment=$' "$DIR/new.desktop")" ]; then
+	echo "[merge] Comment in metadata.desktop is empty!"
+	sed -i '/^Comment\[/ d' "$DIR/new.desktop"
+fi
+if [ ! -z "$(grep '^Keywords=$' "$DIR/new.desktop")" ]; then
+	echo "[merge] Keywords in metadata.desktop is empty!"
+	sed -i '/^Keywords\[/ d' "$DIR/new.desktop"
+fi
+
+# Place translations at the bottom of the desktop file.
+translatedLines=`cat "$DIR/new.desktop" | grep "]="`
+if [ ! -z "${translatedLines}" ]; then
+	sed -i '/^Name\[/ d; /^GenericName\[/ d; /^Comment\[/ d; /^Keywords\[/ d' "$DIR/new.desktop"
+	if [ "$(tail -c 2 "$DIR/new.desktop" | wc -l)" != "2" ]; then
+		# Does not end with 2 empty lines, so add an empty line.
+		echo "" >> "$DIR/new.desktop"
+	fi
+	echo "${translatedLines}" >> "$DIR/new.desktop"
+fi
+
+# Cleanup
+mv "$DIR/new.desktop" "$DIR/../metadata.desktop"
+rm "$DIR/template.desktop"
+rm "$DIR/LINGUAS"
+
+#---
 # Populate ReadMe.md
+echo "[merge] Updating translate/ReadMe.md"
 sed -i -E 's`share\/plasma\/plasmoids\/(.+)\/translate`share/plasma/plasmoids/'"${plasmoidName}"'/translate`' ./ReadMe.md
 if [[ "$website" == *"github.com"* ]]; then
 	sed -i -E 's`\[new issue\]\(https:\/\/github\.com\/(.+)\/(.+)\/issues\/new\)`[new issue]('"${website}"'/issues/new)`' ./ReadMe.md
@@ -133,4 +220,4 @@ sed -i '/^|/ d' ./ReadMe.md # Remove status table from ReadMe
 cat ./Status.md >> ./ReadMe.md
 rm ./Status.md
 
-echo "[merge] Done merging messages"
+echo "[merge] Done"
